version: '3.8'
services:
  postgres-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
  
  mongo-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: mongo-nest
    ports:
      - 27017:27017

  redis-db:
    image: redis
    ports:
      - 6379:6379

  web-api:
    build:
      context: ./ytb-sharing-be
      dockerfile: Dockerfile
    container_name: web-api-c
    ports:
      - 9000:9000
    expose:
      - 9000
    depends_on:
      - mongo-db
      - redis-db
      - postgres-db

  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ./ytb-sharing-fe/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web-api

volumes:
  postgres-data:
  redis-data:
  mongo-data:
